app.py
#!/usr/bin/env python3

from dotenv import load_dotenv

# Load environment variables from '.env' file.
load_dotenv()

from coloprevent import create_app

application = create_app()

if __name__ == "__main__":
    application.run(host="0.0.0.0", port=8000)

coloprevent/__init__.py
from flask import Flask
from .ui import blueprint as ui_blueprint
from .config import Config
from .admin import init_admin
from lbrc_flask import init_lbrc_flask, ReverseProxied
from lbrc_flask.security import init_security, Role, User
from lbrc_flask.celery import init_celery


def create_app(config=Config):
    app = Flask(__name__)
    app.wsgi_app = ReverseProxied(app.wsgi_app)
    app.config.from_object(config)

    TITLE = 'coloprevent'

    with app.app_context():
        init_lbrc_flask(app, TITLE)

        init_security(app, user_class=User, role_class=Role)
        init_admin(app, TITLE)
        init_celery(app, TITLE)

    app.register_blueprint(ui_blueprint)

    return app

coloprevent/model/__init__.py
from sqlalchemy.orm import Mapped, mapped_column
from datetime import date
from lbrc_flask.database import db


class Ordered(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    equipment: Mapped[str] 
    date_ordered: Mapped[date]
    total_requested: Mapped[str]

coloprevent/ui/__init__.py
from flask.blueprints import Blueprint
from flask_security import login_required
from lbrc_flask.database import db


blueprint = Blueprint("ui", __name__, template_folder="templates")

# Login required for all views
@blueprint.before_request
@login_required
def before_request():
    pass


@blueprint.record
def record(state):
    if db is None:
        raise Exception(
            "This blueprint expects you to provide " "database access through database"
        )


from .views import *

coloprevent/ui/views/__init__.py
__all__ = [
 "consumables"
]

coloprevent/ui/views/consumables.py
from flask import render_template, redirect,url_for
from wtforms import StringField,DateField,IntegerField,SubmitField
from wtforms.validators import DataRequired
from lbrc_flask.forms import FlashingForm
from lbrc_flask.database import db
from coloprevent.model import Ordered
from .. import blueprint


#create sql tables 


#creating forms 

class RequestForm(FlashingForm):
    equipment = StringField('Equipment', validators=[DataRequired()])
    total_requested =IntegerField('Total requested', validators=[DataRequired()])
    date_requested =DateField('Date requested', validators=[DataRequired()])


class DeleteData(FlashingForm):
    submit = SubmitField('Delete')

class EditData(FlashingForm):
    equipment = StringField('Equipment', validators=[DataRequired()])
    total_requested =IntegerField('Total requested', validators=[DataRequired()])
    date_requested =DateField('Date requested', validators=[DataRequired()])
  


#creating config for sql tables

#secret ket for wtforms 



@blueprint.route('/', methods=['GET', 'POST'])
def index():
    ordered = db.session.execute(db.select(Ordered).order_by(Ordered.id)).scalars()
    ordered_list=[]
    for queried in ordered:
        ordered_list.append(queried)

    return render_template("ui/home.html", ordered_list=ordered_list)

@blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = RequestForm()
    if form.validate_on_submit():
            new_order =Ordered (
                equipment= form.equipment.data,
                date_ordered = form.date_requested.data,
                total_requested = form.total_requested.data                
                )
            db.session.add(new_order)
            db.session.commit()
    
            return redirect(url_for("ui.index"))
        
            
            

    return render_template("ui/add.html", form=form)



@blueprint.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    delete_id = id
    if id== delete_id:
        query_del = db.session.execute(db.select(Ordered).where(Ordered.id == delete_id)).scalar()
        db.session.delete(query_del)
        db.session.commit()
        return redirect(url_for("ui.index"))
    return render_template('ui/delete.html', id=id)
    
        

    

@blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    edit_id = id
    if id== edit_id:
        query_edit = db.session.execute(db.select(Ordered).where(Ordered.id == edit_id)).scalar()
        prev_equip = query_edit.equipment
        prev_total_req = query_edit.total_requested
        prev_date_ordered= query_edit.date_ordered
        ed_form=EditData(equipment=prev_equip,total_requested=prev_total_req, date_requested=prev_date_ordered) 
       

    
    if ed_form.validate_on_submit():
        
            query_edit.equipment= ed_form.equipment.data
            query_edit.date_ordered = ed_form.date_requested.data
            query_edit.total_requested = ed_form.total_requested.data
            db.session.add(query_edit)
            db.session.commit()
            return redirect(url_for("ui.index"))
        

    return render_template('ui/edit.html', ed_form = ed_form, id=id)

coloprevent/ui/views/home.py
from .. import blueprint
from flask import render_template, request, url_for
from lbrc_flask.forms import SearchForm
from lbrc_flask.database import db
from sqlalchemy import select
from lbrc_flask.security import User
from wtforms import HiddenField, StringField
from wtforms.validators import Length
from lbrc_flask.forms import FlashingForm
from lbrc_flask.response import refresh_response


class EditUserForm(FlashingForm):
    id = HiddenField('id')
    first_name = StringField('First Name', validators=[Length(max=50)])
    last_name = StringField('Last Name', validators=[Length(max=50)])


@blueprint.route("/old")
def index():
    search_form = SearchForm(formdata=request.args, search_placeholder='Search email addresses')

    q = select(User)

    if search_form.search.data:
        q = q.filter(User.email.like(f'%{search_form.search.data}%'))

    users = db.paginate(
        select=q,
        page=search_form.page.data,
        per_page=5,
        error_out=False,
    )

    return render_template(
        "ui/index.html",
        users=users,
        search_form=search_form,
    )


@blueprint.route("/another")
def another():
    return render_template("ui/another.html")


@blueprint.route("/dialog")
def dialog():
    return render_template("ui/dialog.html")


@blueprint.route("/edit/<int:id>", methods=['GET', 'POST'])
def edit(id):
    user = db.get_or_404(User, id)

    form = EditUserForm(obj=user)

    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        db.session.add(user)
        db.session.commit()
        return refresh_response()

    return render_template(
        "lbrc/form_modal.html",
        title=f"Edit User {user.full_name}",
        form=form,
        url=url_for('ui.edit', id=id),
    )

coloprevent/ui/templates/ui/add.html
{% extends "ui/menu_page.html" %}
{% from "lbrc/form_macros.html" import render_form_fields, render_button_bar %}
{% block menu_page_content %}
<section class="container">

    <header>
<h2>Add a new supplies request</h2>
</header>
<form method="POST" action="{{url_for ('ui.add')}}">
    <fieldset>

  
    {{ render_form_fields(form) }}
    {{ render_button_bar ('ui.add') }}
   

</fieldset>
</form>
</section>
{% endblock %}

coloprevent/ui/templates/ui/another.html
{% extends "ui/menu_page.html" %}

{% block menu_page_content %}
<section class="container">
    <header>
        <h2>Another Page</h2>
    </header>
</section>
{% endblock %}

coloprevent/ui/templates/ui/delete.html
{% extends "ui/menu_page.html" %}

{% block title %} Delete {% endblock %}

{% block menu_page_content %}


<h3>Do you wish to delete? </h3>

<form method="POST" action="{{url_for('delete', id=id)}}">
    {{ del_form.csrf_token }}

<p>This action is permanent</p>

    {{del_form.submit }} 
</form>


{% endblock %}

coloprevent/ui/templates/ui/dialog.html
{% extends "lbrc/modal.html" %}

{% block content %}
    <h2>This is a dialog</h2>
{% endblock %}

coloprevent/ui/templates/ui/edit.html
{% extends "ui/menu_page.html" %}
{% from "lbrc/form_macros.html" import render_form_fields, render_button_bar %}
{% block menu_page_content %}

<section class="container">
<h1>Add a new supplies request</h1>
<form method="POST" action="{{url_for('ui.edit', id=id)}}">
        {{ ed_form.csrf_token }}
        <fieldset>
        {{ render_form_fields(ed_form) }}
        {{ render_button_bar ('ui.edit') }}

</form>
</section>
{% endblock %}

coloprevent/ui/templates/ui/home.html
{% extends "ui/menu_page.html" %}

{% block menu_page_content %}
<section class="container">
    <header>
        <h2>Home page</h2>

        <div class="button_bar"> 
        <a class="icon add" href="{{url_for ('ui.add')}}" role="button">add</a>
        </div>


    </header>

    <table>


        <tr>
          <th></th>
          <th>ID</th>
          <th>Equipment</th>
          <th>Date ordered</th>
          <th>Total requested</th>
        </tr>
      
      
        {% for item in ordered_list %}

      
        <tr>
        <td> <a class="icon delete" href="{{url_for('ui.delete', id=item.id)}}"></a>
              <a class="icon edit" href="{{url_for('ui.edit', id=item.id)}}"></a>
              </td>
         
      
            <td>{{item.id}}</td>
            <td>{{item.equipment}}</td>
            <td>{{item.date_ordered}}</td>
            <td>{{item.total_requested}}</td>
      
      
    

              
      
          </tr>
        {% endfor %}
      
      
      
      </table>

</section>

{% endblock %}

coloprevent/ui/templates/ui/index.html
{% extends "ui/menu_page.html" %}
{% from "lbrc/form_macros.html" import render_form_fields, render_field_and_submit %}
{% from "lbrc/pagination.html" import render_pagination, pagination_summary %}

{% block menu_page_content %}
<section class="container">
    <header>
        <h2>A Page</h2>

        <form action="{{ url_for('ui.index') }}" method="GET" enctype="multipart/form-data">
            <fieldset>
                {{ render_form_fields(search_form) }}

                <div class="button_bar">
                    <a class="icon upload" href="javascript:;" title="Upload Study Data" hx-get="{{ url_for('ui.dialog' ) }}" hx-target="body" hx-swap="beforeend" role="button">Show Dialog</a>
                </div>
            </fieldset>
        </form>
    </header>

    {{ pagination_summary(users, 'users') }}

    <ul class="panel_list">
        {% for u in users.items %}
            <li>
                <header class="flex_two_left_grow">
                    <h3>{{u.full_name}}</h3>
                    <nav class="link_list">
                        <a title="Edit user {{ u.full_name }}" href="javascript:;" hx-get="{{ url_for('ui.edit', id=u.id) }}" hx-target="body" hx-swap="beforeend" class="icon edit"></a>
                    </nav>
                </header>
                <dl class="columns">
                    <dt>Name</dt>
                    <dd>{{ u.full_name }}</dd>
                    <dt>Email</dt>
                    <dd>{{ u.email }}</dd>
                    <dt>Last Logged In</dt>
                    <dd>{{ last_login_at | datetime_humanize }}</dd>
                </dl>
           </li>
        {% endfor %}
    </ul>

    {{ render_pagination(users, 'ui.index', form=search_form) }}

</section>
{% endblock %}

coloprevent/ui/templates/ui/menu_page.html
{% extends "lbrc/page.html" %}


{% block page_content %}
  <nav class="main_menu">
    <div class="container">
      <menu>
        <li><a href="{{url_for('ui.index')}}" icon="icon home">Home</a></li>
      
      </menu>
      <menu>
        {% if current_user.is_admin %}
          <li>
            <a>Admin</a>
            <menu>
              <li><a href="{{url_for('admin.index')}}">Maintenance</a></li>
            </menu>
          </li>
          {% endif %}
          <li>
            <a>{{ current_user.full_name }}</a>
            <menu>
              <li><a href="{{ url_for_security('logout') }}">Log Out</a></li>
            </menu>
          </li>
        </menu>
    </div>
  </nav>

  {% block menu_page_content %}{% endblock %}

{% endblock %}

coloprevent/ui/templates/ui/submissions.html
{% extends "ui/menu_page.html" %}

{% block title %} Submissions {% endblock %}

{% block menu_page_content %}

<table class="table">


  <tr>
    <th>ID</th>
    <th>Equipment</th>
    <th>Date ordered</th>
    <th>Total requested</th>
  </tr>


  {% for item in ordered_list %}

  <tr>

      <td>{{item.id}}</td>
      <td>{{item.equipment}}</td>
      <td>{{item.date_ordered}}</td>
      <td>{{item.total_requested}}</td>




        <td><a href="{{url_for('delete', id=item.id)}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-x-fill" viewBox="0 0 16 16">
          <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1M6.854 7.146 8 8.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 9l1.147 1.146a.5.5 0 0 1-.708.708L8 9.707l-1.146 1.147a.5.5 0 0 1-.708-.708L7.293 9 6.146 7.854a.5.5 0 1 1 .708-.708"/>
        </svg></a> </td>

        <td><a href="{{url_for('edit', id=item.id)}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
        </svg></a></td>
   

    </tr>
  {% endfor %}



</table>



{% endblock %}